#[macro_use]
pub mod skill;
pub mod absorb_shield;
pub mod assa_blade_dash;
pub mod assa_phase_prism;
pub mod basic_attack;
pub mod basic_ranged_attack;
pub mod brutal_test_skill;
pub mod cure;
pub mod falcon_carry;
pub mod fire_bomb;
pub mod firewall;
pub mod gaz_turret;
pub mod gaz_xplod_charge;
pub mod heal;
pub mod lightning;
pub mod mounting;
pub mod poison;
pub mod wiz_pyroblast;
